apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: medicine-registry-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicine-registry-api
  template:
    metadata:
      labels:
        app: medicine-registry-api
    spec:
      containers:
      - name: medicine-registry-api
        image: kamilkorczakgmailcom/medicine.registry:latest
        ports:
        - containerPort: 80
kind: Service
metadata:
  name: medicine-registry-service
spec:
  type: LoadBalancer
  selector:
    app: medicine-registry-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80